const buttonInformation = [
  {
    text: "Pagos de Transito",
    icon: "fa fa-file-text-o",
    link: "#",
    img: "none",
    imgFit: undefined,
    color: "#42a5f5",
  },
  {
    text: "Encuesta de Satisfacción",
    icon: "fa fa-list-alt",
    link: "#",
    img: "none",
    imgFit: undefined,
    color: "#4caf50",
  },
  {
    text: "Denuncia contra la corrupcion",
    icon: "fa fa-user-secret",
    link: "#",
    img: "none",
    imgFit: undefined,
    color: "#ff9800",
  },
  {
    text: "Buzon de sugerencias",
    icon: "fa fa-envelope-o",
    link: "#",
    img: "none",
    imgFit: undefined,
    color: "#42a5f5",
  },
  {
    text: "Planeacion y estadistica",
    icon: "fa fa-bar-chart",
    link: "#",
    img: "none",
    imgFit: undefined,
    color: "#4caf50",
  },
  {
    text: "PSE",
    icon: "none",
    link: "#",
    img: "./image/BotonPSE.png",
    imgFit: false,
    color: "#ff9800",
  },
  {
    text: "POT",
    icon: "none",
    link: "#",
    img: "./image/icono pot.png",
    imgFit: true,
    color: "#fff",
  },
];

export default buttonInformation;
